import type { Metadata } from "next";
import { Outfit, Geist } from "next/font/google";
import "./globals.css";
import "react-tooltip/dist/react-tooltip.css";
import "mapbox-gl/dist/mapbox-gl.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${outfit.className} min-h-full flex flex-col dark:bg-gray-900`}
      >
        <ThemeProvider>{children}</ThemeProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
