import type { Metadata } from "next";
import { Outfit, Geist, Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import "react-tooltip/dist/react-tooltip.css";
import "mapbox-gl/dist/mapbox-gl.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const outfit = Outfit({
  subsets: ["latin"],
});

// UI font — used for body text, tables, forms, labels
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

// Display font — used for headings and hero text
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${plusJakartaSans.className} min-h-full flex flex-col dark:bg-gray-900`}
      >
        <ThemeProvider>{children}</ThemeProvider>
        <Toaster richColors position="top-right" />
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
