import type { Metadata } from "next";
import { redirect } from "next/navigation";
import "react-tooltip/dist/react-tooltip.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthProvider";
import { SidebarProvider } from "@/context/SidebarContext";
import AdminLayoutClient from "@/app/(protected)/AdminLayoutClient";
import { getCurrentUserServer } from "@/lib/auth/getCurrentUserServer";

export const metadata: Metadata = {
  title: "Admin dashboard",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const profile = await getCurrentUserServer();

  if (!profile) {
    redirect("/login");
  }

  return (
    <SidebarProvider>
      <AuthProvider initialUser={profile}>
        <AdminLayoutClient>{children}</AdminLayoutClient>
        <Toaster richColors position="top-right" />
      </AuthProvider>
    </SidebarProvider>
  );
}
