import type { Metadata } from "next";
import AdminLayoutClient from "@/app/(admin)/AdminLayoutClient";

export const metadata: Metadata = {
  title: "Admin dashboard",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AdminLayoutClient>{children}</AdminLayoutClient>;
}
