import type { Metadata } from "next";
import AdminLayoutClient from "@/app/(admin)/AdminLayoutClient";
import createClient from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { getProfile } from "@/lib/services/helper/getProfile";
import { AuthProvider } from "@/context/AuthProvider";
import { getCurrentUser } from "@/lib/autth/getCurrentUser";

export const metadata: Metadata = {
  title: "Admin dashboard",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/login");
  }

  console.time("getCurrentUser");
  const profile = await getCurrentUser();
  console.timeEnd("getCurrentUser");
  console.log(profile);

  return (
    <AuthProvider initialUser={profile}>
      <AdminLayoutClient>{children}</AdminLayoutClient>
    </AuthProvider>
  );
}
