import type { Metadata } from "next";
import AdminLayoutClient from "@/app/(admin)/AdminLayoutClient";
import createClient from "@/lib/supabase/server";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Admin dashboard",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/auth/login");
  }

  return <AdminLayoutClient>{children}</AdminLayoutClient>;
}
