export const ERROR_CODES = {
  // Authentication
  UNAUTHORIZED: "UNAUTHORIZED",
  SESSION_EXPIRED: "SESSION_EXPIRED",

  // Authorization
  FORBIDDEN: "FORBIDDEN",
  ROLE_NOT_ALLOWED: "ROLE_NOT_ALLOWED",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",

  // Resource
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  CONFLICT: "CONFLICT",

  // Profile / User
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  COLLEGE_NOT_ASSIGNED: "COLLEGE_NOT_ASSIGNED",

  // Database
  DATABASE_ERROR: "DATABASE_ERROR",

  // Department module
  DEPARTMENT_FETCH_FAILED: "DEPARTMENT_FETCH_FAILED",
  DEPARTMENT_CREATE_FAILED: "DEPARTMENT_CREATE_FAILED",
  DEPARTMENT_UPDATE_FAILED: "DEPARTMENT_UPDATE_FAILED",
  DEPARTMENT_DELETE_FAILED: "DEPARTMENT_DELETE_FAILED",

  // Generic
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
